### ISSUE TITLE
use a package manager for the Dockerfile

### ISSUE THREAD

**Issue by zandbelt** [flix-tech/openresty-oidc-proxy#1]
Nice project :-) Wouldn't it be better to use a package manager like luarocks or opm to pull in the dependencies of lua-resty-openidc here: https://github.com/flix-tech/openresty-oidc-proxy/blob/master/Dockerfile#L12 ?

**Comment by hanikesn** [comment]
It certainly would, but the last time I checked alpine based openresty container didn't include luarocks. But that might have changed in the meantime.

**Comment by nielsole** [comment]
I built a version with luarocks and it inflated image size by factor ~3 to ~260Mb. This is quite a big hit considering that we use this as a sidecar-container for every service.
Also I did not really see a benefit as our dependencies will likely not change anytime soon and version upgrades are easily done manually.
